# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: About
    url: /about/
    weight: 20
  - name: People
    url: /people/
    weight: 30
  - name: Research
    url: /research/
    weight: 40
  - name: Events
    url: /events/
    weight: 50
  - name: News
    url: /news/
    weight: 60
  - name: Opportunities
    url: /opportunities/
    weight: 70
